(() => {
  const statusOptions = ['À appeler','Pas de réponse','Rappeler','RDV fixé','Intéressé','Devis envoyé','Vente / client','Pas intéressé','Numéro invalide','Ne plus contacter'];
  const sourceOptions = ['Site web','Assistant virtuel','Recommandation','Réseaux sociaux','Salon / événement','Appel entrant'];
  const seedProspects = [
    {id:'p1',priority:'A',company:'Atelier du Volcan',city:'Saint-Pierre',contact:'Emma Rivière',phone:'06 00 00 01 01',sector:'Construction / BTP',source:'Site web',status:'À appeler',nextDate:'2026-10-08',nextAction:'Premier appel',owner:'Conseiller',need:'Multirisque professionnelle',note:'Atelier artisanal en développement.'},
    {id:'p2',priority:'A',company:'Lagon Bleu Services',city:'Saint-Gilles-les-Bains',contact:'Yann Hoarau',phone:'06 00 00 02 02',sector:'Tourisme & hôtellerie',source:'Recommandation',status:'Rappeler',nextDate:'2026-10-07',nextAction:'Rappel demandé',owner:'Conseiller',need:'Responsabilité civile professionnelle',note:'Souhaite reparler de sa couverture cette semaine.'},
    {id:'p3',priority:'A',company:'Bourbon Mobilité',city:'Le Port',contact:'Sarah Payet',phone:'06 00 00 03 03',sector:'Auto & mécanique',source:'Réseaux sociaux',status:'Intéressé',nextDate:'2026-10-09',nextAction:'Faire le point sur la flotte',owner:'Conseiller',need:'Flotte automobile',note:'Petite flotte de véhicules utilitaires.'},
    {id:'p4',priority:'B',company:'Jardin Péi',city:'Saint-André',contact:'Lucas Fontaine',phone:'06 00 00 04 04',sector:'Commerce',source:'Assistant virtuel',status:'À appeler',nextDate:'2026-10-10',nextAction:'Premier appel',owner:'Conseiller',need:'Responsabilité civile professionnelle',note:'Demande reçue via le site.'},
    {id:'p5',priority:'B',company:'Cabinet des Hauts',city:'Le Tampon',contact:'Nadia Dijoux',phone:'06 00 00 05 05',sector:'Profession libérale',source:'Site web',status:'RDV fixé',nextDate:'2026-10-12',nextAction:'Rendez-vous téléphonique',owner:'Conseiller',need:'Multirisque professionnelle',note:'Rendez-vous prévu pour préciser les besoins.'},
    {id:'p6',priority:'B',company:'Éclat Bourbon',city:'Saint-Denis',contact:'Maya Rivière',phone:'06 00 00 06 06',sector:'Commerce',source:'Salon / événement',status:'Devis envoyé',nextDate:'2026-10-14',nextAction:'Suivi de proposition',owner:'Conseiller',need:'Multirisque professionnelle',note:'Proposition à expliquer avec un conseiller.'},
    {id:'p7',priority:'C',company:'Cases & Jardins',city:'Saint-Leu',contact:'Thomas Morel',phone:'06 00 00 07 07',sector:'Construction / BTP',source:'Appel entrant',status:'Pas de réponse',nextDate:'2026-10-08',nextAction:'Nouvel essai',owner:'Conseiller',need:'Responsabilité civile professionnelle',note:'Premier appel sans réponse.'},
    {id:'p8',priority:'C',company:'Piton Saveurs',city:'Saint-Paul',contact:'Léna Hoarau',phone:'06 00 00 08 08',sector:'Commerce',source:'Recommandation',status:'À appeler',nextDate:'2026-10-16',nextAction:'Premier appel',owner:'Conseiller',need:'Multirisque professionnelle',note:'Restaurant en phase de préparation.'}
  ];
  const seedClients = [
    {id:'c1',name:'Élodie Payet',phone:'06 92 00 14 28',email:'elodie.payet@example.test',product:'Assurance auto',city:'Saint-Paul',days:4,date:'11 octobre',dateIso:'2026-10-11',premium:'684 € / an',contract:'AUTO-974-1048',note:'Faire le point sur l’assistance et le véhicule de remplacement.'},
    {id:'c2',name:'Mathieu Hoarau',phone:'06 92 00 28 53',email:'mathieu.hoarau@example.test',product:'Multirisque habitation',city:'Saint-Pierre',days:8,date:'15 octobre',dateIso:'2026-10-15',premium:'392 € / an',contract:'HAB-974-2086',note:'Réviser la valeur du mobilier et la couverture dégâts des eaux.'},
    {id:'c3',name:'Nadia Fontaine',phone:'06 92 00 36 77',email:'nadia.fontaine@example.test',product:'Complémentaire santé',city:'Saint-Denis',days:13,date:'20 octobre',dateIso:'2026-10-20',premium:'126 € / mois',contract:'SANT-974-3182',note:'Faire le point sur ses besoins en optique et dentaire.'},
    {id:'c4',name:'Lucas Rivière',phone:'06 92 00 45 91',email:'lucas.riviere@example.test',product:'Assurance professionnelle',city:'Saint-André',days:21,date:'28 octobre',dateIso:'2026-10-28',premium:'918 € / an',contract:'PRO-974-4271',note:'Vérifier l’évolution de l’activité et du matériel assuré.'},
    {id:'c5',name:'Anaïs Dijoux',phone:'06 92 00 59 04',email:'anais.dijoux@example.test',product:'Assurance emprunteur',city:'Le Tampon',days:35,date:'12 novembre',dateIso:'2026-11-12',premium:'54 € / mois',contract:'EMP-974-5390',note:'Préparer un échange sur les garanties emprunteur.'}
  ];
  const storeKey='a974-crm-workspace';
  let state=loadState();
  let activeCall=null,timer=null,seconds=0,currentPage=1;
  const pageSize=8;
  const $=id=>document.getElementById(id);
  const esc=value=>String(value??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
  const isoToday=()=>new Date().toISOString().slice(0,10);
  function loadState(){try{const raw=JSON.parse(localStorage.getItem(storeKey));return{prospects:Array.isArray(raw?.prospects)?raw.prospects:seedProspects.map(x=>({...x})),clients:Array.isArray(raw?.clients)?raw.clients.map(c=>({...c,days:Math.ceil((new Date(`${c.dateIso}T12:00:00`)-new Date())/86400000)})):seedClients.map(c=>({...c,days:Math.ceil((new Date(`${c.dateIso}T12:00:00`)-new Date())/86400000)})),calls:Array.isArray(raw?.calls)?raw.calls:[],reminders:Array.isArray(raw?.reminders)?raw.reminders:[],consents:Array.isArray(raw?.consents)?raw.consents:[]}}catch{return{prospects:seedProspects.map(x=>({...x})),clients:seedClients.map(c=>({...c,days:Math.ceil((new Date(`${c.dateIso}T12:00:00`)-new Date())/86400000)})),calls:[],reminders:[],consents:[]}}}
  async function save(){try{localStorage.setItem(storeKey,JSON.stringify(state));const response=await fetch('/api/crm/state',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(state)});if(!response.ok)throw new Error('save');return true}catch{return false}}
  async function syncServer(){try{const response=await fetch('/api/crm',{cache:'no-store'});if(!response.ok)throw new Error('load');const remote=await response.json();if(['prospects','clients','calls','reminders','consents'].some(k=>Array.isArray(remote[k])&&remote[k].length)){state={...state,...remote};if(!state.prospects.length)state.prospects=seedProspects.map(x=>({...x}));if(!state.clients.length)state.clients=seedClients.map(c=>({...c,days:Math.ceil((new Date(`${c.dateIso}T12:00:00`)-new Date())/86400000)}));}else{await save()}localStorage.setItem(storeKey,JSON.stringify(state));renderDashboard();return true}catch{return false}}
  function toast(text){const el=$('deskToast');el.textContent=text;el.classList.add('visible');clearTimeout(el.timer);el.timer=setTimeout(()=>el.classList.remove('visible'),3200)}
  function fmtDate(value){if(!value)return '—';return new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(`${value}T12:00:00`))}
  function shortDate(value){if(!value)return 'À planifier';return new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'short'}).format(new Date(`${value}T12:00:00`))}
  function setView(name){document.querySelectorAll('.desk-view').forEach(el=>el.classList.toggle('active',el.id===`view-${name}`));document.querySelectorAll('.desk-nav [data-section]').forEach(el=>el.classList.toggle('active',el.dataset.section===name));const labels={dashboard:'Tableau de bord',prospects:'Prospects & appels',clients:'Clients',contracts:'Contrats & échéances',history:'Journal des appels'};$('deskCrumb').textContent=labels[name]||'CRM';$('deskSidebar').classList.remove('open');window.scrollTo({top:0,behavior:'smooth'});if(name==='dashboard')renderDashboard();if(name==='prospects')renderProspects();if(name==='clients')renderClients();if(name==='contracts')renderContracts();if(name==='history')renderHistory()}
  function badgeClass(status){if(status==='À appeler')return 'todo';if(status==='Rappeler'||status==='Pas de réponse')return 'callback';if(status==='Intéressé'||status==='RDV fixé')return 'warm';if(status==='Devis envoyé'||status==='Vente / client')return 'won';if(status==='Ne plus contacter'||status==='Pas intéressé')return 'muted';return 'todo'}
  function pipeline(){const order=['À appeler','Rappeler','Pas de réponse','RDV fixé','Intéressé','Devis envoyé','Vente / client','Pas intéressé','Ne plus contacter'];return order.map(status=>({status,count:state.prospects.filter(p=>p.status===status).length}))}
  function fillFilters(){const fill=(id,values)=>{const select=$(id),prior=select.value,first=select.options[0];select.replaceChildren(first);[...new Set(values)].sort().forEach(value=>{const option=document.createElement('option');option.value=value;option.textContent=value;select.appendChild(option)});if([...select.options].some(o=>o.value===prior))select.value=prior};fill('filterStatus',statusOptions);fill('filterSource',state.prospects.map(p=>p.source));fill('filterSector',state.prospects.map(p=>p.sector))}
  function renderDashboard(){const today=isoToday();$('crmDate').textContent=`${new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date()).toLocaleUpperCase('fr-FR')} · LA RÉUNION`;const pending=state.prospects.filter(p=>['À appeler','Rappeler','Pas de réponse'].includes(p.status));const callbacks=state.prospects.filter(p=>p.status==='Rappeler'||p.status==='Pas de réponse');const quotes=state.prospects.filter(p=>p.status==='Devis envoyé'||p.status==='Intéressé');const renewals=state.clients.filter(c=>{c.days=Math.ceil((new Date(`${c.dateIso}T12:00:00`)-new Date())/86400000);return c.days>=0&&c.days<=30});$('kpiProspects').textContent=pending.length;$('kpiFollowups').textContent=callbacks.length;$('kpiQuotes').textContent=quotes.length;$('kpiRenewals').textContent=renewals.length;$('prospectBadge').textContent=pending.length;$('pipelineTotal').textContent=state.prospects.length;$('sourceTotal').textContent=state.prospects.length;
    const total=Math.max(1,state.prospects.length);$('pipelineBars').innerHTML=pipeline().map(x=>`<button class="desk-pipeline-row" data-pipeline-status="${esc(x.status)}"><span>${esc(x.status)}</span><i><b style="width:${Math.max(x.count?4:0,x.count/total*100)}%"></b></i><strong>${x.count}</strong></button>`).join('');
    const sources=[...new Set(state.prospects.map(p=>p.source))].map(source=>({source,count:state.prospects.filter(p=>p.source===source).length})).sort((a,b)=>b.count-a.count);const colors=['#56c5a6','#7678f5','#41a7f6','#efb75d','#ec7797','#55b5c2'];$('sourceLegend').innerHTML=sources.slice(0,5).map((x,i)=>`<div><i style="--source:${colors[i%colors.length]}"></i><span>${esc(x.source)}</span><b>${x.count}</b></div>`).join('');$('sourceLegend').style.setProperty('--donut',sources.map((x,i)=>`${colors[i%colors.length]} ${i?0:0}`).join(','));document.querySelector('.desk-donut').style.background=`conic-gradient(${sources.reduce((acc,x,i)=>{const prev=sources.slice(0,i).reduce((n,v)=>n+v.count,0),start=prev/total*100,end=(prev+x.count)/total*100;return acc.concat(`${colors[i%colors.length]} ${start}% ${end}%`)},[]).join(',')})`;
    const tasks=[...state.prospects.filter(p=>p.nextDate<=today&&['Rappeler','Pas de réponse','À appeler'].includes(p.status)),...state.prospects.filter(p=>p.status==='RDV fixé')].sort((a,b)=>a.nextDate.localeCompare(b.nextDate)).slice(0,4);$('todayTasks').innerHTML=tasks.length?tasks.map(p=>`<button class="desk-task" data-call-id="${esc(p.id)}"><span class="desk-task-icon ${p.status==='RDV fixé'?'meeting':''}">${p.status==='RDV fixé'?'▣':'☎'}</span><span><b>${esc(p.company)}</b><small>${esc(p.nextAction)} · ${esc(p.contact)}</small></span><time>${p.nextDate<=today?'Aujourd’hui':shortDate(p.nextDate)}</time><i>›</i></button>`).join(''):'<div class="desk-no-task"><span>✓</span><b>Rien d’urgent pour le moment</b><small>Lancez une session d’appels pour avancer votre suivi.</small></div>';
    $('renewalPreview').innerHTML=renewals.slice(0,3).map(c=>`<div class="desk-renewal"><span class="desk-renewal-icon">▤</span><span><b>${esc(c.name)}</b><small>${esc(c.product)}</small></span><strong>${c.days} j</strong></div>`).join('');
    document.querySelectorAll('[data-pipeline-status]').forEach(el=>el.onclick=()=>{setView('prospects');$('filterStatus').value=el.dataset.pipelineStatus;renderProspects()});document.querySelectorAll('[data-call-id]').forEach(el=>el.onclick=()=>openCall(el.dataset.callId));document.querySelectorAll('[data-kpi]').forEach(el=>el.onclick=()=>{const k=el.dataset.kpi;setView(k==='renewals'?'contracts':'prospects');if(k==='quotes')$('filterStatus').value='Devis envoyé';if(k==='followups')$('filterStatus').value='Rappeler';renderProspects()});
  }
  function filteredProspects(){const q=$('prospectSearch').value.trim().toLocaleLowerCase('fr'),status=$('filterStatus').value,source=$('filterSource').value,sector=$('filterSector').value,priority=$('filterPriority').value;return state.prospects.filter(p=>(!q||[p.company,p.contact,p.phone,p.city,p.sector,p.need].some(v=>String(v||'').toLocaleLowerCase('fr').includes(q)))&&(!status||p.status===status)&&(!source||p.source===source)&&(!sector||p.sector===sector)&&(!priority||p.priority===priority)&&(!$('myProspects').checked||p.owner==='Conseiller'))}
  function renderProspects(){fillFilters();const matches=filteredProspects(),pages=Math.max(1,Math.ceil(matches.length/pageSize));currentPage=Math.min(currentPage,pages);const start=(currentPage-1)*pageSize,shown=matches.slice(start,start+pageSize);$('prospectRows').innerHTML=shown.map(p=>`<tr><td><span class="desk-priority prio-${p.priority.toLowerCase()}">${esc(p.priority)}</span></td><td><button class="desk-company-button" data-open-prospect="${esc(p.id)}"><b>${esc(p.company)}</b><small>${esc(p.city)}</small></button></td><td>${esc(p.contact)}</td><td><button class="desk-phone-button" data-call-id="${esc(p.id)}">${esc(p.phone)}</button></td><td>${esc(p.sector)}</td><td><span class="desk-source-chip">${esc(p.source)}</span></td><td><span class="desk-status ${badgeClass(p.status)}">${esc(p.status)}</span></td><td>${p.nextDate?`<small>${fmtDate(p.nextDate)}</small><br>`:''}<span class="desk-next-action">${esc(p.nextAction||'—')}</span></td><td><button class="desk-row-menu" data-call-id="${esc(p.id)}" title="Ouvrir la session d’appel">⋯</button></td></tr>`).join('');$('prospectCount').textContent=state.prospects.length;$('prospectEmpty').hidden=shown.length>0;$('pageSummary').textContent=matches.length?`Affichage de ${start+1} à ${Math.min(start+pageSize,matches.length)} sur ${matches.length} prospects`:'Aucun résultat';$('pageNumber').textContent=`${currentPage} / ${pages}`;$('prevPage').disabled=currentPage<=1;$('nextPage').disabled=currentPage>=pages;document.querySelectorAll('[data-call-id]').forEach(b=>b.onclick=()=>openCall(b.dataset.callId));document.querySelectorAll('[data-open-prospect]').forEach(b=>b.onclick=()=>showProspect(b.dataset.openProspect))}
  function renderClients(){$('clientCount').textContent=`${state.clients.length} clients`;const colors=['mint','sand','lavender','blue','peach'];$('clientCards').innerHTML=state.clients.map((c,i)=>`<article class="desk-client-card"><div class="desk-client-card-head"><span class="desk-contact-avatar ${colors[i%colors.length]}">${esc(c.name.split(/\s+/).map(x=>x[0]).slice(0,2).join(''))}</span><span class="desk-status warm">Client actif</span></div><h2>${esc(c.name)}</h2><p>${esc(c.city)} · ${esc(c.phone)}</p><div class="desk-client-contract"><span>CONTRAT</span><b>${esc(c.product)}</b><small>${esc(c.contract)}</small></div><div class="desk-client-card-foot"><span>Prochaine échéance<br><b>${esc(c.date)}</b></span><span class="desk-client-due">${c.days} jours</span></div></article>`).join('')}
  function renderContracts(){$('contractSummary').innerHTML=`<div><small>CONTRATS ACTIFS (FICTIFS)</small><b>${state.clients.length}</b></div><div><small>ÉCHÉANCES SOUS 30 JOURS</small><b>${state.clients.filter(c=>c.days>=0&&c.days<=30).length}</b></div><div><small>RELANCES ENVOYÉES (SIMULATION)</small><b>${state.reminders.length}</b></div>`;$('contractRows').innerHTML=state.clients.map(c=>`<tr><td><b>${esc(c.name)}</b><small class="desk-cell-sub">${esc(c.city)}</small></td><td>${esc(c.product)}</td><td><span class="desk-source-chip">${esc(c.contract)}</span></td><td>${esc(c.premium)}</td><td>${esc(c.date)} <span class="desk-status callback">${c.days} j</span></td><td><button class="desk-small-action" data-client-call="${esc(c.id)}">Envoyer relance (simulation)</button></td></tr>`).join('');document.querySelectorAll('[data-client-call]').forEach(b=>b.onclick=()=>prepareReminder(b.dataset.clientCall))}
  async function prepareReminder(id){const client=state.clients.find(c=>c.id===id);if(!client)return;const reminder={id:`r${Date.now()}`,clientId:client.id,name:client.name,product:client.product,contract:client.contract,scheduledDate:isoToday(),status:'Message envoyé (simulation)',channel:'SMS simulé',message:`Bonjour ${client.name.split(' ')[0]}, votre contrat ${client.product} arrive à échéance le ${client.date}. Souhaitez-vous convenir d’un échange avec votre conseiller Assurances 974 pour faire le point sur vos besoins ?`,createdAt:new Date().toISOString()};state.reminders.unshift(reminder);const saved=await save();renderContracts();renderDashboard();toast(saved?'Message envoyé (simulation) et enregistré dans le journal.':'Relance simulée dans cette session. Aucun SMS réel envoyé.')}
  function renderHistory(){$('callLog').innerHTML=[...state.calls].reverse().map(call=>`<article class="desk-log-item"><span class="desk-log-icon">☎</span><div><b>${esc(call.company)}</b><small>${esc(call.outcome)} · ${esc(call.note||'Aucune note ajoutée')}</small></div><time>${esc(call.when)}</time></article>`).join('')+([...state.reminders].map(r=>`<article class="desk-log-item"><span class="desk-log-icon">✉</span><div><b>Relance préparée · ${esc(r.name)}</b><small>${esc(r.status)} · ${esc(r.message)}</small></div><time>${fmtDate(r.scheduledDate)}</time></article>`).join(''))||'<div class="desk-no-task"><span>◷</span><b>Aucune activité enregistrée</b><small>Les appels simulés et relances préparées apparaîtront ici.</small></div>'}
  function nextProspect(){const priority={A:1,B:2,C:3};return state.prospects.filter(p=>['À appeler','Rappeler','Pas de réponse'].includes(p.status)&&p.status!=='Ne plus contacter'&&p.consent!==false).sort((a,b)=>priority[a.priority]-priority[b.priority]||(a.nextDate||'9999').localeCompare(b.nextDate||'9999'))[0]}
  function openCall(id){const prospect=state.prospects.find(p=>p.id===id)||nextProspect();if(!prospect){toast('Aucun prospect à appeler pour le moment.');return}activeCall=prospect;seconds=0;$('callAvatar').textContent=prospect.contact.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase();$('callTitle').textContent=prospect.contact;$('callCompany').textContent=`${prospect.company} · ${prospect.city}`;$('callPhone').textContent=prospect.phone;$('callStatusLabel').textContent='Prêt à démarrer · simulation';$('callTimer').textContent='00:00';$('callNote').value='';$('callResult').hidden=true;$('startSimCall').hidden=false;$('saveCall').hidden=true;$('callScript').textContent=`Bonjour ${prospect.contact.split(' ')[0]}, je suis conseiller chez Assurances 974. Vous avez demandé des informations concernant ${prospect.need.toLowerCase()}. Est-ce que vous avez quelques minutes pour que nous puissions comprendre votre activité et les garanties que vous recherchez ?`;$('callOutcome').innerHTML=statusOptions.map(s=>`<option>${esc(s)}</option>`).join('');$('callOutcome').value=prospect.status==='À appeler'?'Pas de réponse':prospect.status;$('callNextDate').value=prospect.nextDate||'2026-10-09';$('callModal').hidden=false}
  function startSimulation(){$('startSimCall').hidden=true;$('callResult').hidden=false;$('saveCall').hidden=false;$('callStatusLabel').textContent='Simulation en cours';timer=setInterval(()=>{seconds++;$('callTimer').textContent=`${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`},1000)}
  function closeModal(id){$(id).hidden=true;if(timer){clearInterval(timer);timer=null}}
  async function saveCall(){if(!activeCall)return;const outcome=$('callOutcome').value,nextDate=$('callNextDate').value,idx=state.prospects.findIndex(p=>p.id===activeCall.id);if(idx>=0){state.prospects[idx].status=outcome;state.prospects[idx].nextDate=nextDate;state.prospects[idx].nextAction=outcome==='Rappeler'?'Rappel téléphonique':outcome==='RDV fixé'?'Confirmer le rendez-vous':outcome==='Devis envoyé'?'Suivi de proposition':outcome==='Pas de réponse'?'Nouvel essai':'Suivi conseiller';state.prospects[idx].note=$('callNote').value.trim()||state.prospects[idx].note}const when=new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date());state.calls.push({id:Date.now(),prospectId:activeCall.id,company:activeCall.company,contact:activeCall.contact,outcome,note:$('callNote').value.trim(),when,duration:$('callTimer').textContent});await save();closeModal('callModal');renderDashboard();toast(`Appel simulé enregistré · ${outcome}`)}
  function showProspect(id){const p=state.prospects.find(x=>x.id===id);if(!p)return;const backdrop=document.createElement('div');backdrop.className='desk-modal-backdrop';backdrop.innerHTML=`<section class="desk-modal" role="dialog" aria-modal="true"><button class="desk-modal-x" aria-label="Fermer">×</button><div class="desk-eyebrow">FICHE PROSPECT · DONNÉES FICTIVES</div><h2>${esc(p.company)}</h2><p class="desk-profile-sub">${esc(p.sector)} · ${esc(p.city)}</p><div class="desk-profile-grid"><div><small>Contact</small><b>${esc(p.contact)}</b></div><div><small>Téléphone fictif</small><b>${esc(p.phone)}</b></div><div><small>Assurance recherchée</small><b>${esc(p.need)}</b></div><div><small>Source · priorité</small><b>${esc(p.source)} · ${esc(p.priority)}</b></div><div><small>Statut</small><b>${esc(p.status)}</b></div><div><small>Prochaine action</small><b>${esc(p.nextAction)} · ${fmtDate(p.nextDate)}</b></div><div class="wide"><small>Note de suivi</small><p>${esc(p.note||'Aucune note pour le moment.')}</p></div></div><div class="desk-form-actions"><button class="desk-secondary-button" data-close-profile>Fermer</button><button class="desk-primary-button" data-profile-call>☎ Simuler un appel</button></div></section>`;document.body.appendChild(backdrop);backdrop.querySelectorAll('[data-close-profile],.desk-modal-x').forEach(b=>b.onclick=()=>backdrop.remove());backdrop.querySelector('[data-profile-call]').onclick=()=>{backdrop.remove();openCall(p.id)}}
  function newProspect(){ $('prospectForm').reset();$('prospectModal').hidden=false }
  async function addProspect(event){event.preventDefault();const d=new FormData(event.currentTarget),prospect={priority:String(d.get('priority')),company:String(d.get('company')).trim(),city:String(d.get('city')).trim(),contact:String(d.get('contact')).trim(),phone:String(d.get('phone')).trim(),sector:String(d.get('sector')),source:String(d.get('source')),nextDate:isoToday(),nextAction:'Premier appel',need:String(d.get('need')),note:'Consentement recueilli lors de la création de la fiche.',consent:true,consentPurpose:'Enregistrement de la demande et rappel par un conseiller'};try{const response=await fetch('/api/crm/prospects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prospect,consent:true})});if(!response.ok)throw new Error('server');const result=await response.json();state={...state,...result.data}}catch{prospect.id=`p${Date.now()}`;prospect.status='À appeler';prospect.owner='Conseiller';state.prospects.unshift(prospect);state.consents.push({prospectId:prospect.id,accepted:true,purpose:prospect.consentPurpose,acceptedAt:new Date().toISOString()});await save()}closeModal('prospectModal');setView('prospects');toast('Prospect créé après validation du consentement.')}
  async function analyzeCrm(){const panel=$('crmAnalysis');panel.hidden=false;$('analysisText').textContent='Analyse des rappels, devis et échéances en cours…';$('analyzeCrm').disabled=true;try{const response=await fetch('/api/crm/analyze',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});const result=await response.json();$('analysisText').textContent=result.analysis||'Analyse indisponible.';$('analysisSource').textContent=result.source==='groq'?'Analyse IA · Groq · données du CRM':'Analyse locale · configuration IA optionnelle';}catch{$('analysisText').textContent='Analyse indisponible. Vérifiez que le serveur de démonstration est démarré.'}finally{$('analyzeCrm').disabled=false}}
  function exportCsv(){const headers=['Priorité','Entreprise','Ville','Contact','Téléphone','Secteur','Source','Statut','Prochaine action','Date','Assurance recherchée','Note'];const lines=[headers,...state.prospects.map(p=>[p.priority,p.company,p.city,p.contact,p.phone,p.sector,p.source,p.status,p.nextAction,p.nextDate,p.need,p.note])].map(row=>row.map(value=>`"${String(value??'').replace(/"/g,'""')}"`).join(';'));const blob=new Blob(['\ufeff'+lines.join('\r\n')],{type:'text/csv;charset=utf-8'}),url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download='assurances974-prospects-demo.csv';link.click();URL.revokeObjectURL(url);toast('Export CSV des prospects fictifs téléchargé.')}
  function parseCsvLine(line){const result=[];let cell='',quoted=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'&&line[i+1]==='"'&&quoted){cell+='"';i++}else if(ch==='"')quoted=!quoted;else if((ch===';'||ch===',')&&!quoted){result.push(cell.trim());cell=''}else cell+=ch}result.push(cell.trim());return result}
  function importCsv(file){const reader=new FileReader();reader.onload=()=>{const lines=String(reader.result).replace(/^\uFEFF/,'').split(/\r?\n/).filter(Boolean);if(lines.length<2){toast('Le fichier ne contient aucun prospect à importer.');return}const data=lines.slice(1).map((line,i)=>{const c=parseCsvLine(line);return{id:`pi${Date.now()}-${i}`,priority:c[0]||'B',company:c[1]||'Prospect importé',city:c[2]||'La Réunion',contact:c[3]||'Contact à préciser',phone:c[4]||'Non renseigné',sector:c[5]||'Autre',source:c[6]||'Import CSV',status:statusOptions.includes(c[7])?c[7]:'À appeler',nextDate:c[9]||'2026-10-07',nextAction:c[8]||'Premier appel',need:c[10]||'À préciser',owner:'Conseiller',note:c[11]||''}});state.prospects.push(...data);save();renderDashboard();renderProspects();toast(`${data.length} prospect(s) fictif(s) importé(s).`)};reader.readAsText(file,'utf-8')}
  document.querySelectorAll('.desk-nav [data-section]').forEach(b=>b.onclick=()=>setView(b.dataset.section));document.querySelectorAll('[data-section-link]').forEach(b=>b.onclick=()=>setView(b.dataset.sectionLink));$('deskMenuToggle').onclick=()=>$('deskSidebar').classList.toggle('open');$('deskCloseMenu').onclick=()=>$('deskSidebar').classList.remove('open');$('dashboardCallNext').onclick=$('prospectsCallNext').onclick=()=>openCall();$('newProspectButton').onclick=newProspect;$('prospectForm').addEventListener('submit',addProspect);document.querySelectorAll('[data-close-modal]').forEach(b=>b.onclick=()=>{closeModal('callModal');closeModal('prospectModal')});$('startSimCall').onclick=startSimulation;$('saveCall').onclick=saveCall;$('analyzeCrm').onclick=analyzeCrm;$('closeAnalysis').onclick=()=>$('crmAnalysis').hidden=true;$('prospectModal').addEventListener('click',e=>{if(e.target===$('prospectModal'))closeModal('prospectModal')});$('callModal').addEventListener('click',e=>{if(e.target===$('callModal'))closeModal('callModal')});$('exportProspects').onclick=exportCsv;
  ['prospectSearch','filterStatus','filterSource','filterSector','filterPriority','myProspects'].forEach(id=>$(id).addEventListener(id==='prospectSearch'?'input':'change',()=>{currentPage=1;renderProspects()}));$('resetFilters').onclick=()=>{$('prospectSearch').value='';['filterStatus','filterSource','filterSector','filterPriority'].forEach(id=>$(id).value='');$('myProspects').checked=false;currentPage=1;renderProspects()};$('prevPage').onclick=()=>{currentPage--;renderProspects()};$('nextPage').onclick=()=>{currentPage++;renderProspects()};$('importProspects').onclick=()=>$('csvFile').click();$('csvFile').onchange=e=>{if(e.target.files[0])importCsv(e.target.files[0]);e.target.value=''};$('deskNotifButton').onclick=()=>toast(`${state.prospects.filter(p=>p.nextDate<='2026-10-07'&&['Rappeler','Pas de réponse','À appeler'].includes(p.status)).length} actions à consulter aujourd’hui.`);
  const outcomes=$('callOutcome');statusOptions.forEach(s=>{const o=document.createElement('option');o.value=s;o.textContent=s;outcomes.appendChild(o)});
  renderDashboard();syncServer();
})();
